### ISSUE TITLE
NumberFormat Exception on Android Plot

### ISSUE THREAD

**Issue by jigar1859** [Lightstreamer/Lightstreamer-example-AdvStockList-client-android#2]
`08-19 19:59:25.694 4505-4505/com.lightstreamer.simple_demo.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.lightstreamer.simple_demo.android, PID: 4505
                                                                                     android.view.InflateException: Binary XML file line #46: Binary XML file line #46: Error inflating class com.androidplot.xy.XYPlot
                                                                                     Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class com.androidplot.xy.XYPlot
                                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                                         at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                         at com.lightstreamer.simple_demo.android.DetailsFragment.onCreateView(DetailsFragment.java:85)
                                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                                      Caused by: java.lang.NumberFormatException: For input string: "@2131034204"
                                                                                         at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
                                                                                         at java.lang.Float.parseFloat(Float.java:459)
                                                                                         at com.androidplot.util.Configurator.parseFloatAttr(Configurator.java:150)
                                                                                         at com.androidplot.util.Configurator.inflateParams(Configurator.java:236)
                                                                                         at com.androidplot.util.Configurator.configure(Configurator.java:322)
                                                                                         at com.androidplot.util.Configurator.configure(Configurator.java:286)
                                                                                         at com.androidplot.Plot.loadAttrs(Plot.java:371)
                                                                                         at com.androidplot.Plot.init(Plot.java:316)
                                                                                         at com.androidplot.Plot.<init>(Plot.java:249)
                                                                                         at com.androidplot.xy.XYPlot.<init>(XYPlot.java:150)
                                                                                         at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                                         at com.lightstreamer.simple_demo.android.DetailsFragment.onCreateView(DetailsFragment.java:85) 
                                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
                                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
                                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229) 
                                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                                         at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
`

`com.lightstreamer.simple_demo.android.DetailsFragment.onCreateView(DetailsFragment.java:85) `

this piece of code is a below:
`View view = inflater.inflate(R.layout.details_view, container, false);`

Few other Details: Using Android Studio 3.0 Canary. and little older version of the library... However tired upgrading to latest.. issue still persists...

complie 'com.androidplot:androidplot-core:0.6.1' OR
compile "com.androidplot:androidplot-core:1.5.1"

Please advise... 
Thanks in Advance

**Comment by acarioni** [comment]
Compiling the demo using Gradle and executing it in a device emulator running Android 5.1 (API level 22), everything works fine. 
Which environment are you using?

**Comment by jigar1859** [comment]
Using 
Android Studio Canary Build 3.0 Preview, 
Google Pixel XL Device, Android O Beta 
Gradle:
'com.android.tools.build:gradle:3.0.0-beta2'

Compiling Against:

compileSdkVersion 26
buildToolsVersion "26.0.0"

minSdkVersion 15
targetSdkVersion 26

Hope this helps... 

- Jigar

**Comment by acarioni** [comment]
The problem seems to be caused by the version 3 of Gradle. 
Downgrading gradle-wrapper to gradle-3.5 and com.android.tools.build:gradle to version 2.2.3 should fix the problem.
